version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8

    commands:
      - npm install

  build:
    commands:
      - npm run build
      - aws cloudformation package --template-file template.yaml --output-template-file output.yaml --s3-bucket ${c_s3_target_bucket} --s3-prefix SAM
artifacts:
  type: zip
  files:
    - template.yaml
    - output.yaml
